# Generated by Django 5.0.3 on 2024-03-12 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loans',
            fields=[
                ('identifier', models.AutoField(primary_key=True, serialize=False)),
                ('nominal_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ip_address', models.CharField(max_length=45)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('bank', models.CharField(max_length=100)),
                ('client', models.CharField(max_length=100)),
            ],
        ),
    ]
